### ISSUE TITLE
How can I connect from python?

### ISSUE THREAD

**Issue by jakubbares** [acupofjose/elasticstore#19]
Hey,
I have an API in python and need to connect to the search collection from there.
Once I run your repo in docker, will I be able to connect to it? Should I start an express server? 
Can I connect directly to elastic search and will I be able to see the search collection?
Thanks

**Comment by acupajoe** [comment]
The `search` collection is a firestore collection that is essentially proxied by this repo. 

So you'll need to monitor the `search` collection using the firestore SDK in your app with this code running to supply a proper result. 

That's about all I can answer with the information you've given!

If you need more info - I'll need something more about what you're trying to do.

**Comment by jakubbares** [comment]
I am trying to make elastic search index my articles in FireStore and provide full text search over them. Also I would like to use document embeddings for each article to compare them based on their vector representation. Elastic search should have this functionality.

So all I have to do is run the repo you provided and will be able to query the virtual /search collection from anywhere?
