### ISSUE TITLE
Converting Elastic response.hits.hits to a map changes the sort order

### ISSUE THREAD

**Issue by nikmartin** [acupofjose/elasticstore#22]
By default, elastic search results are sorted based on _score, and can be sorted any number of ways based on the query . in SearchHandler.ts:70, the search results are coerced into a map using the _id as the key. This ends up sorting the map by _id vs. array ordinal. If you are using elastic as a search engine, this will provide inaccurate search results, or you'll have to re-sort the map based on _score.

**Comment by acupofjose** [comment]
@nikmartin oooh good catch! Care to make a pull request?

**Comment by nikmartin** [comment]
Well I'm not sure of the original motivation or requirement to convert it to a map. The fix for my own use case was to just keep it in an array and handle the array on the client (which was also easier in the long run, a simple forEach)

**Comment by acupofjose** [comment]
@nikmartin this was fixed in [cd97b19](https://github.com/acupofjose/elasticstore/blob/cd97b193fb42c9e1a932456c87cd3a41be2da259/src/util/SearchHandler.ts) thanks for using elasticstore and sharing the feedback!

**Comment by acupofjose** [comment]
This has been fixed in https://github.com/acupofjose/elasticstore/blob/cd97b193fb42c9e1a932456c87cd3a41be2da259/src/util/SearchHandler.ts

**Comment by nikmartin** [comment]
Are you aware of the 'new-new' elasticsearch node library at `@elastic/elasticsearch`? It has type definitions built in, and only takes a few changes on the config/connection setup to upgrade to.

**Comment by acupofjose** [comment]
I am now! Thanks for putting it out there - I've updated it and included some additional refactoring in the latest tag [@1.0.2](https://github.com/acupofjose/elasticstore/releases/tag/1.0.2)
