### ISSUE TITLE
Error in `FS_ADDED` handler [doc@h3XhjEJQJ4EZ6KXLSgIE]: illegal_argument_exception

### ISSUE THREAD

**Issue by Gongsta** [acupofjose/elasticstore#23]
Hey, I found this repository while looking for a simple integration between elasticsearch and firestore. I managed to connect to firestore and run elasticsearch locally, but I'm getting the error above, an illegal_argument_exception. That's all the error message tells me, and I have no idea how to debug this.

For more context, I have a collection of jobs documents hosted on firebase, and I want to sync it with elasticsearch with the goal of doing smarter queries. The code below is all I put inside the references.ts file.

const references: Array<Reference> = [
  {
    collection: "jobs",
    index: "jobs",
  }
]

Please let me know how I can fix this. Thanks!

**Comment by acupofjose** [comment]
You could add a `console.log(e)` above [line 169](https://github.com/acupofjose/elasticstore/blob/fd6fdd0d31d0866444dc3dcdd8092f47d129426b/src/util/FirestoreHandler.ts#L169)

**Comment by Gongsta** [comment]
Alright, I still have no idea what is the cause of the error. I've attached a snippet of the bug log.
<img width="1061" alt="Screen Shot 2020-07-08 at 12 46 36 PM" src="https://user-images.githubusercontent.com/43485866/86946943-19d5b300-c119-11ea-9bdc-8e178bed40e0.png">

I followed the instructions, do you have any clue why I might have this error?

**Comment by acupofjose** [comment]
@Gongsta could you do a [GET mapping request from elasticsearch](https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-get-mapping.html) on the index you're talking about, show what you have in `references.ts` and give the content of the firestore document at `h3XhjEJQJ4EZ6KXLSgIE`?

**Comment by Gongsta** [comment]
I'm so sorry, I am relatively new to elasticsearch, I fixed the problem by upgrading elasticsearch on my computer from 6.8 to the latest version. Everything else got fixed! Thank you for the help anyways
