### ISSUE TITLE
Add failed then all update failed as well

### ISSUE THREAD

**Issue by alaindixon** [acupofjose/elasticstore#24]
Hi I have an issue with your library.

I don't know why but sometimes the create failed.

Error in `FS_ADDED` handler [doc@VDPUYRBpKg3sJO4nwMgd]: [mapper_parsing_exception] failed to parse
Error in `FS_MODIFIED` handler [doc@VDPUYRBpKg3sJO4nwMgd]: [document_missing_exception] [orders][VDPUYRBpKg3sJO4nwMgd]: document missing, with { index_uuid="3wbl0DqXSqGYyHsx5rOcbQ" & shard="0" & index="orders" }
Error in `FS_MODIFIED` handler [doc@VDPUYRBpKg3sJO4nwMgd]: [document_missing_exception] [orders][VDPUYRBpKg3sJO4nwMgd]: document missing, with { index_uuid="3wbl0DqXSqGYyHsx5rOcbQ" & shard="0" & index="orders" }
Error in `FS_MODIFIED` handler [doc@VDPUYRBpKg3sJO4nwMgd]: [document_missing_exception] [orders][VDPUYRBpKg3sJO4nwMgd]: document missing, with { index_uuid="3wbl0DqXSqGYyHsx5rOcbQ" & shard="0" & index="orders" }

**Comment by acupofjose** [comment]
@alaindixon, thanks for using the library! Is your firestore document `VDPUYRBpKg3sJO4nwMgd` conforming to the same types as the other documents in your collection? 

Elasticsearch defines the mapping of an index based off the document it first receives (or the mapping you specify in the configuration). If it receives a document that does not conform to the existing type mapping, it will reject it. (i.e. trying to insert an `Object` where a `float` should be)

You can see a similar thread here: https://github.com/elastic/elasticsearch-py/issues/579

**Comment by alaindixon** [comment]
Thank you for your very  quick response, awesome.
Basically I could order several products, I've got a field "menuDetail", I think it was null in the first place.
What would you recommand?  

![Capture d’écran 2020-07-08 à 17 51 37](https://user-images.githubusercontent.com/5199552/86941006-b4e38280-c143-11ea-8103-92a01bf9d8f3.png)

![Capture d’écran 2020-07-08 à 17 46 48](https://user-images.githubusercontent.com/5199552/86941050-c3319e80-c143-11ea-8622-dfbbbabef90d.png)

![Capture d’écran 2020-07-08 à 17 46 32](https://user-images.githubusercontent.com/5199552/86941060-c6c52580-c143-11ea-8d69-226e16f20c74.png)

**Comment by acupofjose** [comment]
Yep! That would do it.

There are some tutorials out there on how to update/change mappings in Elasticsearch. 

If your app is still in heavy development, my approach would be to blow out the existing index, insert a fully defined document, and reinsert everything into elasticsearch. But that's just me.

Here's a blog entry on changing the mapping:
https://www.elastic.co/blog/changing-mapping-with-zero-downtime

As this isn't a problem with the library in particular, I'll close this issue. If you end up having other problems with it, please let me know!
