### ISSUE TITLE
Mapping include_type_name should be removed at this point

### ISSUE THREAD

**Issue by teebu** [acupofjose/elasticstore#28]
Types are no longer a thing. The `include_type_name: true` should be removed, now with 7.8.0

https://www.elastic.co/guide/en/elasticsearch/reference/7.x/removal-of-types.html

**Comment by acupofjose** [comment]
@all-contributors add @teebu for bugs

**Comment by acupofjose** [comment]
@teebu thank you for submitting some bug reports (especially with ideas/fixes in your comments!) They have been merged and you have been added to our contributor list for bug reporting.
