### ISSUE TITLE
Poor error handling when pushing data to same index, will throw already exists error.

### ISSUE THREAD

**Issue by teebu** [acupofjose/elasticstore#32]
When pushing data to same index (references 2 tables push to same es index), each will check if index exists and try to create it because they are called at the same time. It will start to throw `already_exists` errors on second worker. 

I had to add try/catch error handling and a `delay(5000)` in the class Worker to give some breathing room for each worker to initialize.

**Comment by acupofjose** [comment]
Ooo interesting! I like the solution that you gave, so I'll implement it like that as well. Thanks @teebu

**Comment by teebu** [comment]
Your solution is using exponential delay, which is interesting and probably unnecessary. I just used a simple static delay for each worker. 

```
const delay = (ms: number) => new Promise(res => setTimeout(res, ms))

export default class Worker {
  static async register(client: Client) {
    const firestoreHandlers: Array<FirestoreCollectionHandler> = []
    for (const record of Config.references) {
      firestoreHandlers.push(new FirestoreCollectionHandler(client, record))      
      await delay(5000) // delay initial worker startup
    }
    //new SearchHandler(client)
  }
}
```
