### ISSUE TITLE
TypeError: Cannot read property 'request' of undefined at FirestoreCollectionHandler.existsApi 

### ISSUE THREAD

**Issue by calvin-sentry** [acupofjose/elasticstore#41]
Coming from the ElasticSearch package, not sure why this isn't working.

TypeError: Cannot read property 'request' of undefined at FirestoreCollectionHandler.existsApi (/app/node_modules/@elastic/elasticsearch/api/api/exists.js:62:25) at Queuer.<anonymous> (/app/lib/util/Queuer.js:91:59) at step (/app/lib/util/Queuer.js:33:23) at Object.next (/app/lib/util/Queuer.js:14:53) at /app/lib/util/Queuer.js:8:71 at new Promise (<anonymous>) at __awaiter (/app/lib/util/Queuer.js:4:12) at Timeout._onTimeout (/app/lib/util/Queuer.js:85:49) at listOnTimeout (internal/timers.js:554:17) at processTimers (internal/timers.js:497:7)

Could this potentially be my ElasticSearch version?

**Comment by acupofjose** [comment]
Is elastic store running at all? Or just throwing this error and exiting? Does it connect to elasricsearch? Are you running an older version of elastic search?

**Comment by calvin-sentry** [comment]
It connects to elasticsearch because I have verified that it is creating indexes. It also logs the output of connecting.

**Elasticstore is running and connecting with firestore,  however, it is failing with:**

Error in `FS_ADDED` handler [doc@4Kb3XP2BhCOpiZoOWlfEqdLFNQG2]: Cannot read property 'request' of undefined.

It is connecting to elasticsearch via HTTP because I plan to offload the SSL with NGINX proxy:
Connecting to ElasticSearch host quickstart-es-http:9200

I am running elasticsearch: Version "7.9.2" (Docker)

**Comment by calvin-sentry** [comment]
Thank you for you quick response by the way, this is much appreciated.

**Comment by acupofjose** [comment]
Since you're using docker - any chance you can try switching to 7.2.*?

**Comment by calvin-sentry** [comment]
Ok so what I did was removed the entire Queuing system and got it adding to Elasticsearch. I have to implement a new Queuer.js.

**Comment by acupofjose** [comment]
@calvin-sentry glad you got it working - interesting you had to remove the queuer. If you end up rewriting it - please share! Would love to see what you end up with.

**Comment by tarung** [comment]
> Ok so what I did was removed the entire Queuing system and got it adding to Elasticsearch. I have to implement a new Queuer.js.

I am also facing exact same problem, upgrading any version numbers did not help, As suggested by you, After removing the Queuer, it started working. Thanks

**Comment by calvin-sentry** [comment]
Yeah no problem, but there's an issue of having a lot of records now; I haven't gotten to that functionality working yet. Instead, I might just switch to using firestore functions as I only need to make elasticsearch read-only.

**Comment by alaindixon** [comment]
Hi, I've got exactly the same error, could you help please?
I've tried Elasticsearch 7.8.0 and  7.9.3

`Error in `FS_ADDED` handler [doc@09080d15-caaf-4c61-8003-52c49a82ea96]: Cannot read property 'request' of undefined
TypeError: Cannot read property 'request' of undefined
    at FirestoreCollectionHandler.existsApi (/app/node_modules/@elastic/elasticsearch/api/api/exists.js:62:25)
    at Queuer.<anonymous> (/app/lib/util/Queuer.js:91:59)
    at step (/app/lib/util/Queuer.js:33:23)
    at Object.next (/app/lib/util/Queuer.js:14:53)
    at /app/lib/util/Queuer.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/app/lib/util/Queuer.js:4:12)
    at Timeout._onTimeout (/app/lib/util/Queuer.js:85:49)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)`

**Comment by nareddyt** [comment]
#44 fixes the issue mentioned above.

**Comment by acupofjose** [comment]
Thanks @nareddyt!
