### ISSUE TITLE
TypeError: Cannot read property 'onSnapshot' of undefined

### ISSUE THREAD

**Issue by ElGecko76** [acupofjose/elasticstore#42]
Hi,

I followed your tutorial on Medium (https://medium.com/@acupofjose/wondering-how-to-get-elasticsearch-and-firebases-firestore-to-play-nice-1d84553aa280) and I'm stuck at the last step.

I have an `events` collection on Firestore and a `location` subcollection which has a `geopoint` type field which is called `geopoints` like this:

![Untitled Project](https://user-images.githubusercontent.com/19478137/99720347-ec791880-2aad-11eb-838e-6e09076fa899.jpg)

I added this lines in `references.ts` file without error during the `npm start` command:

```
import { Reference } from "./types"

// Records should be added here to be indexed / made searchable
const references: Array<Reference> = [
  {
    collection: "events",
    subcollection: "location",
    index: "event-location",
    mappings: {
        geopoints: {
          // Elasticsearch's 'geo_point' needs to be specified
          type: "geo_point"
      }
    },
    // Transform data as we receive it from firestore
    transform: (data, parent) => ({
      ...data,
     location:`${data.location.geopoints_latitude},${data.location.geopoints._longitude}`
    })
  },
]

export default references
```

And this is my function in my React project:

```
import firebase from '@config/firebase';

export const getEvents = () => {
  const result = firebase.firestore().collection('search').add({
    request: {
      index: 'events',
      type: 'events',
      body: {},
    },
    response: null
  })

  result.ref.onSnapshot(doc => {
    if (doc.response !== null) {
      console.log(doc.response)
    }
  })
};

```

I get this error after calling `getEvents` function:

> TypeError: Cannot read property 'onSnapshot' of undefined

My goal is to reduce the number of requests to Firestore by retrieving all my events stored in Firestore first and then retrieving my events which have a latitude and longitude of X kilometers radius from a latitude and longitude of a user. So, for now I would like to test if it's functional and I don't need to create a query in `body`.

Do you know where this error can come from? Moreover, I do not understand what the `type` key is for, can you explain me please?

Thank you in advance :)

**Comment by acupofjose** [comment]
@ElGecko76 I believe you're missing an `await`:

```
const result = **await** firebase.firestore().collection('search').add({
    request: {
      index: 'events',
      type: 'events',
      body: {},
    },
    response: null
  })
```

**Comment by ElGecko76** [comment]
Wow thank you for this express response!

Okay thank you for this information, I removed the `type` key.

I already tried to add `await` but same error

**Comment by acupofjose** [comment]
Yessir!

I'm actually a little lost on that code block - I'm unfamiliar with an import for `@config/firebase`. If you're getting an undefined `` that seems to be 


Would it not be:
```typescript
import firebase from '@firebase/app';
import '@firebase/firestore'

export const getEvents = async () => {
  const ref = await firebase.firestore().collection('search')

  ref.onSnapshot(doc => {
    if (doc.response !== null) {
      console.log(doc.response)
    }
  })

  await ref.add({
    request: {
      index: 'events',
      body: {},
    },
    response: null
  })
}

**Comment by acupofjose** [comment]
You should be seeing `search` documents added to the firebase console. Then it's just a matter of displaying them!

**Comment by ElGecko76** [comment]
@acupofjose Thank you! But I get `undefined` in `console.log(doc.response);`

Yep I see this:

![image](https://user-images.githubusercontent.com/19478137/99722661-3e6f6d80-2ab1-11eb-880f-d9c670fc33c8.png)

It is not very useful besides x)

**Comment by acupofjose** [comment]
Ha - yes you'll need to put a query in to actually get some results, try 

```
{
  "request": {
    "index": "events",
    "q": "*"
  },
  "response": null
}
```

**Comment by ElGecko76** [comment]
Still `undefined` and there is written: 

> ResponseError: index_not_found_exception

```
import firebase from '@firebase/app';
import '@firebase/firestore'

export const getEvents = async () => {
  const ref = await firebase.firestore().collection('search')

  ref.onSnapshot(doc => {
    if (doc.response !== null) {
      console.log(doc.response)
    }
  })

  await ref.add({
    request: {
      index: 'events',
      q: '*',
    },
    response: null
  })
}
```

![image](https://user-images.githubusercontent.com/19478137/99722973-cf464900-2ab1-11eb-979d-e4ec938ece5a.png)

**Comment by acupofjose** [comment]
Whoops, I didn't see how you defined the `references.ts` you'll have to use `event-location` as your index

**Comment by ElGecko76** [comment]
@acupofjose There is exactly the same problem but with this index :/

**Comment by acupofjose** [comment]
Cool - I'd check with Kibana then and make sure that elasticstore is actually showing your documents.

My guess is that it will not be showing anything in it. In which case, you should remove the `subcollection: 'location'` from your `references.ts` file. (You aren't actually looking for a subcollection on that document, just a `map`). 

After updating your references, restart `elasticstore` and make sure that the terminal window shows that it has processed a document.

**Comment by ElGecko76** [comment]
@acupofjose thank you, it's better:

![image](https://user-images.githubusercontent.com/19478137/99724581-1d5c4c00-2ab4-11eb-9e59-8ea0e04632a4.png)

On the other hand, it is the entire document that is stored

**Comment by acupofjose** [comment]
You can fix that using the the options available for `references.ts` as listed in the readme. Either using `include`, `exclude` or `transform`.

For instance, using how you already have it set up, you can just mirror the `location.geopoints` to `location` key like this:

```
transform: (data, parent) => ({
     location:`${data.location.geopoints_latitude},${data.location.geopoints._longitude}`
    })
```

**Comment by ElGecko76** [comment]
@acupofjose Thank you very much!! :smile:

**Comment by acupofjose** [comment]
Yep! Happy to.
